apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJrZW5uZHJpY2suamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImVXOXJaVzV1TnpkQVoyMWhhV3d1WTI5dE9sZHBaR0ZoWkVBM053PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson